photoshare/config/routes.rb
Photoshare::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
 
  get "search", to: "photos#title_search"
  get "tag_search", to: "photos#tag_search"
  get "tag_search_form", to: "photos#tag_search_form"

  resources :photos do
    resources :tags, :shallow => true
  end

  resources :users do
    resources :photos, :shallow => true
  end

  get "home/index"

  

root :to => 'home#index', as: 'home'

end

photoshare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoshare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">PhotoTag Gallery</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", home_path %></li>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Photos<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if user_signed_in? %>
                  <li><%= link_to "Upload Photo", new_user_photo_path(current_user.id) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Search by Tag", tag_search_form_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Edit Your Photos", user_photos_path(current_user.id) %></li>
                  <% else %>
                  <li>Sign in to access these features!</li>
                  <% end %>
                </ul>
            </li>
          </ul>
          <%= form_tag "/search", method: "get", class: "navbar-search navbar-left" do %>
            <div class="form-group">
              <div class="input-append">
                <%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search by Title" %>
                <%= button_tag :type => "submit", :class => "btn btn-default" do %>
                  <i class="icon-search"></i>
                <% end %>
              </div>
            </div>
          <% end %>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
            <li class="navbar-text"><p>Welcome, <strong><%= current_user.fname %></strong></p></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li> <%= link_to "Login", new_user_session_path %></li>
          <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>
    
    <div class="row">
      <div class="span6">
        <%= yield %>
      </div>
      <div class="span6">
      </div>
    </div>
  </div>
</body>
</html>