photoshare/config/routes.rb
Photoshare::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
 
  get "search", to: "photos#title_search"
  get "tag_search", to: "photos#tag_search"
  get "tag_search_form", to: "photos#tag_search_form"

  resources :photos do
    resources :tags, :shallow => true
  end

  resources :users do
    resources :photos, :shallow => true
  end

  get "home/index"

  

root :to => 'home#index', as: 'home'

end

photoshare/app/models/photo.rb
class Photo < ActiveRecord::Base

has_many :tags, :dependent => :destroy # if a photo is deleted, so are all its tags
belongs_to :user

mount_uploader :image, ImageUploader

validates :title, presence: true
validates :image, presence: true 

def self.title_search title
  if title
    find(:all, :conditions => ['title LIKE ?', "%#{title}%"])
  else
    find(:all)
  end
end

def self.tag_search key, value
  if key && value
    key = key.capitalize
    value = value.capitalize
    photos = Photo.joins(:tags).where(:tags => {:key => key, :value => value})
  end
  return photos
end

end

photoshare/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 # before_action :set_photo, only: [#:edit, :update, :destroy]
  before_filter :authenticate_user!
  
  # Search photos by title
  def title_search
    @results = Photo.title_search(params[:search])

    if !@results.empty?
      flash[:notice] = "Showing Photos with title \"#{params[:search]}\""
    else
      flash[:alert] = "No Photos were found matching the title \"#{params[:search]}\"" 
    end
    
    return @results
  end

  # search photos by tag
  def tag_search
    @results = Photo.tag_search(params[:key], params[:value])

    if !@results.empty?
      flash[:notice] = "Showing Photos Tagged with Key = \"#{params[:key]}\" and Value =  \"#{params[:value]}\""
    else
      flash[:alert] = "No Photos Found Tagged With Key = \"#{params[:key]}\" and Value =  \"#{params[:value]}\""
    end
    
    return @results
  end
  
  def tag_search_form
  end
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  def new
    @user = User.find(current_user.id)
    @photo = @user.photos.new #new photo in the context of @user
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    if @photo.user != current_user
      redirect_to @photo, alert: 'You cannot edit someone elses photos!'
    end
  end

  # POST /photos
  # POST /photos.json
  def create
    @user = User.find(params[:user_id])
    @photo = Photo.new(photo_params)
    @photo.user = @user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was sucessfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @user = User.find(params[:user_id])
      @photo = @user.photos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image, :user_id)
    end
end

photoshare/app/helpers/photos_helper.rb
module PhotosHelper
end

photoshare/app/views/photos/_form.html.erb
<%= form_for([@user, @photo], :html => { :multipart => true, :class => 'form-signup' }) do |f| %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

        <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
    <div class="actions">
      <%= f.submit class:  "btn btn-lg btn-primary" %>
    </div>
<% end %>

photoshare/app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render 'form' %>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photo.tags.each do |tag| %>
      <tr>
        <td><%= tag.key %></td>
        <td><%= tag.value %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

photoshare/app/views/photos/index.html.erb
<h1>Your Uploaded Photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <% if photo.user_id == current_user.id %>
      <tr>
        <td><%= photo.title %></td>
        <td><%= link_to(image_tag(photo.image_url), photo_path(photo)) %>
        <td><%= link_to 'Edit', edit_photo_path(photo), class: "btn btn-default" %></td>
        <td><%= button_to 'Delete', photo, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_user_photo_path(current_user.id) %>

photoshare/app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', home_path %>

photoshare/app/views/photos/search.html.erb
<h1>Search Photos</h1>
<table>
  <% @results.each do |photo| %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= link_to(image_tag(photo.image_url), photo_path(photo)) %>
    </tr>
  <% end %>
</table>
<% if user_signed_in? %>
<%= link_to "Upload New Photo", new_user_photo_path(current_user.id) %>
<% end %>

photoshare/app/views/photos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>
<p>
  <%= image_tag(@photo.image_url) %>
</p>
<p>
  <table class="table table-condensed">
    <tr>
      <th>Tags</th>
    </tr>
    <% @photo.tags.each do |tag| %>
    <tr>
      <td><%= tag.key %> = <%= tag.value %>=<%= tag.id %></td>
    </tr>
  <% end %>
  </table>
<%#= debug @photo %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Upload Photo', new_user_photo_path(current_user.id) %> |
<%= link_to 'Add Tags', new_photo_tag_path(@photo) %>

photoshare/app/views/photos/tag_search.html.erb
<h1>Search Photos by Tag</h1>
<table>
  <% @results.each do |photo| %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= link_to(image_tag(photo.image_url), photo_path(photo)) %>
    </tr>
  <% end %>
</table>

photoshare/app/views/photos/tag_search_form.html.erb
<%= form_tag "/tag_search", method: "get", class: "form-signin" do %>
  <h2 class="form-signin-heading">Search Photos by Tag</h2>
  <%= text_field_tag :key, params[:key], :autofocus => true, class: "input-block-level", placeholder: "Key" %>
  <%= text_field_tag :value, params[:value], class: "input-block-level", placeholder: "Value"  %>
  <button class="btn btn-lg btn-primary btn-block" type="submit"><i class="icon-search"></i>Search</button>

<% end %>

photoshare/app/views/photos/title_search.html.erb
<h1>Search Photos</h1>
<table>
  <% @results.each do |photo| %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= link_to(image_tag(photo.image_url), photo_path(photo)) %>
    </tr>
  <% end %>
</table>
<% if user_signed_in? %>
<%= link_to "Upload New Photo", new_user_photo_path(current_user.id) %>
<% end %>